# github action main.yml template
name: A workflow for ranked teams
on: push
# job to run index.js with output.text
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v1
      - name: Install Node Dependencies
        run: npm install
      - name: Run the script
        run: node index.js
      - name: Set Username
        run: git config --global user.email "nyshawnburton16@gmail.com"
      - name: Set Name
        run: git config --global user.name "Nyshawn Burton"
      - name: Update the repository
        run: git add . && git commit -m "Added team output file" && git push origin test